language: c

dist: trusty

os:
  - linux

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['gfortran-6']

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install gcc;
      fi

    - gfortran -dumpversion

install:
    - make


