language: python

python:
  - 3.5  
# py35 for old Mac Travis image

dist: trusty

os:
  - linux
  - osx


notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install gcc ncurses;
      fi

install: 
    - export FC=gfortran
    - cd bin
    - cmake ..
    - make
    - cd ..

script:
    - python tests/test.py

