language: c
fast_finish: true

os:
  - linux
  - osx
  
env: FC=gfortran

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc || true;
      brew link --overwrite gcc;
      brew install ncurses;
      export FC=gfortran;
      fi

install: 
    - cd bin
    - cmake ..
    - make


script:
    - ./tetran 1000

