language: c
fast_finish: true

os:
  - linux
#  - osx
# FIXME not sure why travis-ci gives osx segfault.
  
env: FC=gfortran

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc || true;
      brew link --overwrite gcc;
      brew install ncurses;
      export FC=gfortran;
      fi

install: 
  - cd bin
  - cmake ..
  - make


script:
  - make test
    
after_failure:
  - ctest -V

